feat: first version of helm chart
glasskube/operator pull request #126
Opened 2023-05-15 08:18 UTC by thschue

## This PR
* Adds the first version of a helm chart
* Adds simple workflow to release the chart

2023-05-16 11:30 UTC, kosmoz requested changes
Generally the chart works great! :tada: 

I did find some issues though, which we should address.

Also, the CRDs are currently auto-generated and placed in the deploy directory by a gradle task. We should probably do something similar for the chart, however I think it's okay if that's done in a follow-up ticket.

2023-05-16 11:30 UTC, kosmoz commented on charts/glasskube-operator/templates/serviceAccount.yaml
> +  namespace: {{ .Release.Namespace }}
Again, I think the namespace is supplied by helm.

2023-05-17 06:03 UTC, thschue commented on charts/glasskube-operator/templates/deploy.yaml
> +  namespace: {{ .Release.Namespace }}
removed

2023-05-17 06:06 UTC, thschue commented on charts/glasskube-operator/Chart.yaml
> +dependencies:
I investigated a bit and this is not possible. When we remove them, they would have to be installed manually. If we don't provide the option to install the dependencies with the chart, we should either document this (manual installation) or ensure that the application works without them.

2023-05-17 06:06 UTC, thschue commented on charts/glasskube-operator/templates/namespace.yaml
removed

2023-05-17 06:08 UTC, thschue commented on charts/glasskube-operator/values.yaml
> +      memory: 512Mi
updated

2023-05-17 06:09 UTC, thschue commented on charts/glasskube-operator/templates/deploy.yaml
> +      - env:
Changed this to the Release Name (I think you used "glasskube-operator" as the release name?)

2023-05-17 06:10 UTC, thschue commented
> 

Thank you for your review! I addressed the comments, I'd propose that we do the auto-generation of CRDs in a second issue.

2023-06-21 14:28 UTC, kosmoz requested changes
I tried the chart again and it works now. :tada: 

If you could implement the following changes, we would be ready to merge this PR:
- After some discussion, we decided that we would prefer to rename the values identifier `glasskubeOperator` to `operator`.
- Some time has passed since this PR was created (this is our bad…), so it is necessary to add the missing CRDs and update the RBAC manifest.
- We decided to keep the dependencies as part of the chart, but they should be disabled by default. This means that for each dependency there should be a `condition` in the `Chart.yaml` and its default value in `values.yaml` should be set to `false`.
- The `appVersion` can be updated to `0.5.2`.
- The MariaDB Operator version can be updated to `0.15.1`, which the latest version of our operator should be compatible with.

2023-06-30 10:10 UTC, kosmoz approved these changes

2023-06-30 10:11 UTC, merged