feat: Enable Gardener ingress annotations for dns (#250)
glasskube/operator pull request #251
Opened 2023-08-10 12:50 UTC by JensAc

This PR enables the use of Gardener ingress for automatic creation of Dnsentries, when the operator is run on a Gardener-based Kubernetes cluster.

2023-08-10 15:44 UTC, pmig requested changes
Thanks for your contribution :-)

We are happy to support gardener.

Please make sure to not break clusters without this specific config map. A quick test would be to delete the `glasskube-settings` and `shoot-info` config map and restart the operator.

As an additional tip you can forward the MinIO service via:

```
kubectl port-forward -n glasskube-system svc/glasskube-minio 9000
```

and configure it in your local IDE with an additional env var:

`MINIO_HOST_NAME`:`localhost`

So you can connect your operator to a remote cluster.

2023-08-10 15:44 UTC, pmig commented on operator/src/main/kotlin/eu/glasskube/operator/config/ConfigService.kt
> +                CloudProvider.gardener
The use of `!!` is generally  not recommended as it will hide `NullPointerExceptions`. Especially in this case where an Exception is thrown if no config map with the name `shoot-info` can be found.

```
2023-08-10T17:32:09.837+02:00 [ReconcilerExecutor-configgenerator-182] ERROR i.j.o.p.e.ReconciliationDispatcher - Error during event processing ExecutionScope{ resource id: ResourceID{name='glasskube-settings', namespace='glasskube-system'}, version: 168764586} failed. 
java.lang.NullPointerException: Cannot invoke "io.fabric8.kubernetes.api.model.ConfigMap.getData()" because the return value of "io.fabric8.kubernetes.client.dsl.Resource.get()" is null
	at eu.glasskube.operator.config.ConfigService.getDynamicCloudProvider(ConfigService.kt:61)
```

This will break config map creation for non gardener managed clusters. I recommend a solution similar to .. `?.let { it.contains(...) }`.

2023-08-11 07:23 UTC, JensAc commented on operator/src/main/kotlin/eu/glasskube/operator/config/ConfigService.kt
> +                CloudProvider.gardener
Alright, I see. I misunderstood the behavior of `.!!`. So what about?
```
kubernetesClient.configMaps().inNamespace("kube-system")?.withName("shoot-info")?.get()?.data?.get("extensions")?.contains("shoot-dns-service") == true ->
                CloudProvider.gardener

```
I tried this at least, and it seams to be working fine, even the safe call chain does not look very pretty.
Sorry, I am new to Kotlin and tried to search the web for the reason why you've suggested a solution based on `let` but did not find any appropriate explanation. Maybe, you could point me somewhere?

2023-08-16 14:28 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/config/ConfigService.kt
> +                CloudProvider.gardener
> Alright, I see. I misunderstood the behavior of `.!!`. So what about?
> 
> ```
> kubernetesClient.configMaps().inNamespace("kube-system")?.withName("shoot-info")?.get()?.data?.get("extensions")?.contains("shoot-dns-service") == true ->
>                 CloudProvider.gardener
> ```
> 
> I tried this at least, and it seams to be working fine, even the safe call chain does not look very pretty. Sorry, I am new to Kotlin and tried to search the web for the reason why you've suggested a solution based on `let` but did not find any appropriate explanation. Maybe, you could point me somewhere?

Yes that should work fine, although I think the first result that can actually be `null` is that of `get()`, so you can omit the first two safe calls. Using `let` (or another [scope function](https://kotlinlang.org/docs/scope-functions.html)) is not necessary here.

(Also, small correction: The `!!` operator does not hide `NullPointerException`s, it raises one if the value is `null`.)

2023-08-29 07:44 UTC, pmig requested changes
We are happy to merge your contribution, with a small improvement - as kosmoz mentioned.

One last thing: Please squash your commits to a single commit following the conventional commit syntax.

2023-08-29 07:44 UTC, pmig commented on operator/src/main/kotlin/eu/glasskube/operator/config/ConfigService.kt
> +            kubernetesClient.configMaps().inNamespace("kube-system")?.withName("shoot-info")?.get()?.data?.get("extensions")?.contains("shoot-dns-service") == true ->
```suggestion
            kubernetesClient.configMaps().inNamespace("kube-system").withName("shoot-info").get()?.data?.get("extensions")?.contains("shoot-dns-service") == true ->
```

as @kosmoz mentioned in his comment:

> I think the first result that can actually be null is that of get(), so you can omit the first two safe calls

2023-08-29 08:16 UTC, JensAc commented
> We are happy to merge your contribution, with a small improvement - as kosmoz mentioned.
> 
> One last thing: Please squash your commits to a single commit following the conventional commit syntax.

I just did that. I am not entirely sure whether this is a good workflow, as I needed a force push in order to rewrite my history to a single commit. Wouldn't it make more sense that you simply "squash and merge"? Anyways, I hope I met your requirements now.

2023-08-29 08:55 UTC, kosmoz approved these changes

2023-08-29 08:56 UTC, merged