feat: Add oidc integration example for nextcloud (#252)
glasskube/operator pull request #253
Opened 2023-08-10 13:00 UTC by JensAc

This PR introduces a very simple example how the integration of oidc could be done. Please let me know what you think about having secret data directly in the `Nextcloud` resource and the `Deployment`. This PR is meant as a starting point for discussion and implementation.

2023-08-10 13:52 UTC, pmig commented
Thanks for your contribution on the first glance it already looks very promissing. We might want to wrap the authentication into a parent object, so we can also support SAML2.0 and make it the interface future proof.

As @kosmoz will be able to review the PR next Wednesday the earliest it might take a little longer this time to get the interface right :-).

2023-08-16 14:52 UTC, kosmoz requested changes
Hi Jens and thank you for your contribution! :rocket: 

I think it makes a lot of sense to support OIDC configuration for the tools that support it. This looks like a good start, however I have some suggestions and questions below.

2023-08-16 14:52 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/NextcloudAppsSpec.kt
> +        val discoveryEndpoint: String
Suggestion: I am not 100% familiar with Nextcloud OIDC but I think most of these properties should have the `@field:Required` annotation. This only affects the generated CRD but it means that Kubernetes will validate those constraints.

2023-08-16 14:52 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudDeployment.kt
> +                                    php $OCC_PATH app:install user_oidc
Question: Why did you go with [`user_oidc`](https://apps.nextcloud.com/apps/user_oidc) rather than [`oidc_login`](https://apps.nextcloud.com/apps/oidc_login)? 

I don't know much about either but the latter seems to be more popular.

2023-08-16 16:27 UTC, JensAc commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/NextcloudAppsSpec.kt
> +        val discoveryEndpoint: String
Most probably you are right. I did not take care for this in this POC implementation.

2023-08-16 16:27 UTC, JensAc commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/NextcloudAppsSpec.kt
> +    val oidc: Oidc? = null
Same as above...

2023-08-16 16:28 UTC, JensAc commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudDeployment.kt
> +                                        --unique-uid=0
Yes, that totally makes sense.

2023-08-16 16:32 UTC, JensAc commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudDeployment.kt
> +                                        --clientsecret=${primary.spec.apps.oidc?.clientSecret} \
Here I am not entirely sure, whether that would make any difference in terms of security considerations, as the credentials will also be part of the `Nextcloud` resource, when adopting this POC implementation. Therefore, I would suggest that we apply the secret independently and simply refer to it in the `Nextcloud` resource and in the `Pod` spec. However, as already stated above, this would break with the description of an application by a single resource.

Of course, we could also follow the track you just proposed.

2023-08-16 16:32 UTC, JensAc commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudDeployment.kt
> +                                    php $OCC_PATH app:install user_oidc
No specific reason. I just stumbled accross the first one and used it for this POC.

2023-09-08 11:52 UTC, JensAc commented
I just iterated once more over this PR and hope that I met your ideas. Once again, I really appreciate a review and will iterate once more if desired.

2023-09-11 14:19 UTC, kosmoz requested changes
Thanks for the update! 

I tested this feature using a local Keycloak and Nextcloud instance and it basically worked out of the box (see below)! :sparkles: 

There are still some smaller improvements/suggestions I would like to propose before we merge this (open for discussion, see below).

2023-09-11 14:19 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudConfigMap.kt
> +                    }
Suggestion: The number of null checks seems kind of redundant here. I think it could be reduced by using `arrayOf()` with the [spread operator](https://kotlinlang.org/docs/functions.html#variable-number-of-arguments-varargs). Something like:

```kt
listOfNotNull(
  // ...
  "log_level" to 2,
  // spread operator here ("*"):
  *spec.apps.oidc?.let {
    arrayOf(
      "oidc_login_provider_url" to it.issuerUrl,
      "oidc_login_logout_url" to spec.host,
      // ...
    )
  }.orEmpty(), // spread requires non-null
  // ...
)
```

2023-09-11 14:19 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudDeployment.kt
> +            }
Thought: These secret keys("clientId" and "clientSecret") are hardcoded. While this is not a problem by itself and I think the names are well-chosen, it is definitely something that should be documented. 

An alternative would be using a set of `SecretKeySelector`s, similar to `S3Spec`, but that would require more changes.

Could you please add one or two sentences about this to the documentation page you created about OIDC configuration?

2023-09-11 14:19 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/NextcloudAppsSpec.kt
> +    data class Oidc(
Thought: During my test using a local Kubernetes cluster, I had to disable TLS verification in the configuration to get it working. While this would obviously be a bad idea for production use-cases, do you think it would make sense to offer this as a configuration parameter for those wanting to quickly try this feature out locally?

2023-09-15 13:11 UTC, JensAc commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudConfigMap.kt
> +                    }
Thanks for that suggestion. I updated the corresponding section

2023-09-15 13:12 UTC, JensAc commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudDeployment.kt
> +            }
I hope that I understood you correctly. I added a table to the docs. Maybe you can double check whether I met your intention.

2023-09-15 13:15 UTC, JensAc commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/NextcloudAppsSpec.kt
> +    data class Oidc(
Actually, I do not really need that. Of course, we could discuss which further options of the oidc_login app should be configurable via the `nextcloud` resource. If you wish, I can add `oidc_login_tls_verify` and also other options. We could also incorporate these from time to time. Just let me know what you prefer.

2023-09-18 08:33 UTC, kosmoz approved these changes
Looks good :+1:

2023-09-18 08:33 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/dependent/NextcloudDeployment.kt
> +            }
Great, thanks!

2023-09-18 08:33 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/apps/nextcloud/NextcloudAppsSpec.kt
> +    data class Oidc(
Alright, we can start simple and extend from there. After all, this would be a non-breaking change.

2023-09-18 08:35 UTC, pmig approved these changes

2023-09-18 08:37 UTC, merged