AWS EKS Support
glasskube/operator pull request #34
Opened 2022-12-17 12:16 UTC by pmig

resolves #27

2022-12-22 12:22 UTC, kosmoz requested changes
Note: I did not test running this change set on an EKS cluster, so this review is mostly concerned with code style and code quality.

2022-12-22 12:22 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoIngress.kt
> +            CloudProvider.minikube -> emptyMap<String, String>()
```suggestion
            CloudProvider.minikube -> emptyMap()
```

2022-12-22 12:22 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoIngress.kt
> +    private fun configureAnnotations(client: KubernetesClient): Map<String, String>? {
```suggestion
    private fun configureAnnotations(client: KubernetesClient): Map<String, String> {
```

2022-12-22 12:22 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoIngress.kt
> +    private fun configureIngressClassName(client: KubernetesClient): String? {
```suggestion
    private fun configureIngressClassName(client: KubernetesClient): String {
```

2022-12-22 12:22 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoIngress.kt
> +    private fun configureIngressClassName(client: KubernetesClient): String? {
I am not sure why the `KubernetesClient` has to be passed as argument to  this function, as it is already available as a class property. The same also applies to `configureAnnotations`

2022-12-22 12:22 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/config/ConfigGenerator.kt
> +class ConfigGenerator(val kubernetesClient: KubernetesClient) : Reconciler<ConfigMap> {
`KubernetesClient` should be private

2022-12-22 12:22 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/Main.kt
> +}
Although fine as it is, I think these functions would be good candidates for single-expression functions, in which case the return type could also be inferred by the compiler.

Reference: https://kotlinlang.org/docs/functions.html#single-expression-functions

2022-12-22 12:22 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/matomo/dependent/MatomoIngress.kt
> +                Pair("alb.ingress.kubernetes.io/group.name", "glasskube")
There are two ways in Kotlin to create a `Pair`. One is using the `Pair` constructor (like here) and the other is using the `to` infix function. Since the latter is already used in this project, I think it would be best to change these lines to use the `to` function as well, so the project style stays consistent.

2022-12-29 11:45 UTC, pmig commented on operator/src/main/kotlin/eu/glasskube/operator/mariadb/MariaDB.kt
> +}
Sadly there is an open bug about this: https://github.com/fabric8io/kubernetes-client/issues/3816 

Due to the [ReconilerUtils uses reflection to check if the `setSpec` ](https://github.com/java-operator-sdk/java-operator-sdk/blob/main/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/ReconcilerUtils.java#L98)method exists.

2023-01-04 10:39 UTC, kosmoz approved these changes

2023-01-04 10:40 UTC, merged