feat: add support for creating velero schedules
glasskube/operator pull request #351
Opened 2023-10-03 15:30 UTC by kosmoz

2023-11-08 09:54 UTC, pmig requested changes
The velero s3 path looks like: `restic/matomo/config` although the backup name is `matomo.matomo-matomo` maybe the dot will not be added to the backup path (which is not ideal)

beside that it works fine :-)

2023-11-08 09:54 UTC, pmig commented on operator/src/main/kotlin/eu/glasskube/operator/apps/common/backup/BackupSpec.kt
> +    val schedule: String = "0 0 4 * * *",
Velero schedule only allows 5 field cron annotation

```
status:
  phase: FailedValidation
  validationErrors:
    - 'invalid schedule: Expected exactly 5 fields, found 6: 0 0 4 * * *
```

2023-11-08 09:54 UTC, pmig commented on operator/src/main/kotlin/eu/glasskube/operator/apps/common/backup/BackupSpec.kt
> +    val schedule: String = "0 0 4 * * *",
It also seems that the schedule doesn't get updated if changed and can't be changed via the CRD

2023-11-08 13:06 UTC, kosmoz commented
> The velero s3 path looks like: `restic/matomo/config` although the backup name is `matomo.matomo-matomo` maybe the dot will not be added to the backup path (which is not ideal)

So, I did some digging and it looks like this is a limitation of Veleros "File System Backup" component. When instructed to create a PodVolumeBackup during a backup, the `BackupRepoReconciler` ensures that a `BackupRepository` exists for the `Pod`s namespace and the `BackupStorageLocation` of the `Backup`, using only the `Pod`s namespace as part of the `resticIdentifier` (regardless of the uploaderType used). 

I think the only workaround for this might be to create a `BackupRepository` before any `Backup`s are scheduled, but I'm not sure if that would work.

2023-11-08 13:11 UTC, kosmoz commented on operator/src/main/kotlin/eu/glasskube/operator/apps/common/backup/BackupSpec.kt
> +    val schedule: String = "0 0 4 * * *",
Fixed

2023-11-08 14:54 UTC, kosmoz commented
added Cloud Storage Backup CronJob for Gitlab and updated Cloud Storage Backup image tag to v0.2.1

2023-11-09 07:56 UTC, pmig approved these changes

2023-11-09 07:57 UTC, merged